### ISSUE TITLE
Revert the changes for calculated ports for Dynamic Cluster offer 

### ISSUE THREAD

**Issue by jacobt123** [wls-eng/arm-oraclelinux-wls#79]
The changes done to remove calculated ports for the Dynamic Cluster offer seems to be causing issues during scale up. This needs to be reverted.

**Comment by gnsuryan** [comment]
I have reverted back the changes to make the calculatedListenPorts set to true.

Reference: https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/commit/f523595bd28ed30c8d6dd36f4f11a82780b483bc

Also, the changes done in the fix for issue#74, for configuring FrontEndHost & Ports have not been included in the dynamic cluster offer as we will not enabling the Application Gateway for the Dynamic Cluster offer, for now.

For the FrontEndHost configuration, I would require the App Gateway hostname, which will not be available, for now.
